DATASET:
  PART_COUNT: 1
  SIZE: 60000
  # PATH: /data/datasets/mnist/tfrecords/mnist-r%02d.tfrecords.%03d
  PATH: /data/datasets/svhn/tfrecords/svhn-r%02d.tfrecords.%03d
  PATH_TEST: /data/datasets/svhn/tfrecords/svhn_test-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 3
  FLIP_IMAGES: False
MODEL:
  # LATENT_SPACE_SIZE: 256
  LATENT_SPACE_SIZE: 128
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 128
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  # MAPPING_LAYERS: 5
  MAPPING_LAYERS: 4
  CHANNELS: 3
  #GENERATOR: "DCGANGenerator"
  #ENCODER: "DCGANEncoder"
  #MAPPING_TO_LATENT: "MappingToLatentNoStyle"
OUTPUT_DIR: svhn_results
TRAIN:
  #ADAM_BETA_0: 0.5
  #ADAM_BETA_1: 0.999
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 4
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 40
  LOD_2_BATCH_8GPU: [128, 128, 128,   64]
  LOD_2_BATCH_4GPU: [128, 128, 128,   64]
  LOD_2_BATCH_2GPU: [128, 128, 128,   64]
  LOD_2_BATCH_1GPU: [128, 128, 128,   64]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.002]
