DATASET:
  PART_COUNT: 16
  SIZE: 202576
  PATH: /data/datasets/celeba/tfrecords/celeba-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 7
MODEL:
  LATENT_SPACE_SIZE: 256
  LAYER_COUNT: 6
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
OUTPUT_DIR: results_z
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 6
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 65
  #                    4       8       16       32       64       128        256       512       1024
  LOD_2_BATCH_8GPU: [512,    256,     128,      64,      32,       32,        32,       32,        32]
  LOD_2_BATCH_4GPU: [512,    256,     128,      64,      32,       32,        32,       32,        16]
  LOD_2_BATCH_2GPU: [128,    128,     128,      64,      32,       32,        16]
  LOD_2_BATCH_1GPU: [128,    128,     128,      64,      32,       16]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015,  0.0015,   0.0015,     0.002,     0.003,    0.003]

  # LEARNING_RATES: [0.0015, 0.0015, 0.0015,  0.0015,  0.0015,   0.0015,     0.002,     0.003,     0.003,]


# chfn -f "Liam Mcgoldrick" liammcgold
# cat /etc/group
# groupmod -g 1011 liammcgold
# usermod -u 1011 liammcgold
# chown -R  liammcgold:liammcgold liammcgold/

# gdemian:x:1003:1003::/home/gdemian:/bin/bash
  #bbsmith1:x:1005:1005::/home/bbsmith1:/bin/bash
  #messagebus:x:101:247:System user; messagebus:/dev/null:/sbin/nologin
  #marcela:x:1006:1006::/home/marcela:/bin/bash
  #qjones:x:1007:1007::/home/qjones:/bin/zsh
  #stpidhorskyi:x:1008:1008::/home/stpidhorskyi:/bin/zsh
  #liammcgold:x:1011:1011::/home/liammcgold:/bin/bash
  #summer_user:x:1012:1012::/home/summer_user:/bin/bash
  #sinan:x:1013:1013::/home/sinan:/bin/bash

  # adduser tmp
  # usermod -aG sudo tmp
 # update-alternatives --install /usr/bin/python python /usr/bin/python3 10
